### ISSUE TITLE
Incantifier Binder scroll knowledge

### ISSUE THREAD

**Issue by mackeyth** [Chris-plus-alphanumericgibberish/dnethack#30]
Incantifier binders receive scrolls of food detection in place of the (stolen) tripe and cram rations in their starting inventory, but they do not know the identity of the scrolls.

**Comment by RikerW** [comment]
Chris stated on IRC/Discord that this was intentional at the time, but not necessarily going to stay in. Also, in the future, [dnao](https://github.com/Chris-plus-alphanumericgibberish/dNAO) is the currently maintained repository for dnh. Issues might be better served over there.

**Comment by mackeyth** [comment]
Got it, thanks.
